### PR TITLE
feat(minecraft)!: remove kanto

### PR DESCRIPTION
**Pull request by LooterToGo**

### CODE REVIEW

**Review by ChipWolf — CHANGES_REQUESTED** [review]
feat(minecraft)!: remove kanto

**Comment by ChipWolf** [comment]
I'll merge this once a backup is taken and stored in GDrive

**Review by ChipWolf — CHANGES_REQUESTED** [review]
Will merge once a backup is taken and stored in GDrive.

**Review by ChipWolf — CHANGES_REQUESTED** [review]
Please resolve merge conflicts

**Comment by LooterToGo** [comment]
Why is pre-commit failing when the file is getting deleted?

**Pull request merged**
